version: "3"

task:
  build:
    desc: Golang Application
    cmds:
    - GOFLAGS=-mod=mod go build -o bin/go-rest-api internal/main.go

  run:
    desc: Run Golang Application
    cmds:
    - GOFLAGS=-mod=mod go run internal/main.go

  swagger.gen:
    desc: Generate Go code
    cmds: 
    - GOFLAGS=-mod=mod go generate github.com/riteshsonawane1372/golang-http/internal github.com/riteshsonawane1372/golang-http/pkg/swagger

  swagger.validate:
      desc: Validate swagger
      cmds:
      - swagger validate pkg/swagger/swagger.yml

    swagger.doc:
      desc: Doc for swagger
      cmds:
      - docker run -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html